// Supabase data access layer.
//
// Design: the app keeps its existing pattern of reading data from plain
// in-memory arrays (`customers`, `invoices`, `deliveryOrders`, `allEditions`
// — exported from src/data/*.ts) so every existing read (`.find`, `.filter`,
// `.map`, etc.) across the app keeps working completely unchanged. What
// changes is where those arrays get filled from: `loadAllData()` below
// fetches everything from Supabase once at app startup and populates them.
//
// Every function that used to just mutate one of those arrays directly
// (push/splice/index-assignment) now does two things: persist the change to
// Supabase first (awaited — if it fails, nothing local changes either, so
// the UI never shows something as saved that wasn't), then apply the same
// change to the local array so the UI updates immediately without needing
// a full reload.

import { supabase } from './supabaseClient'
import { allEditions, deductStock, type Edition, type VolumeRecord } from '../data/publicationData'
import {
  customers, invoices, deliveryOrders, fulfillments,
  type Customer, type CustomerSubscription,
  type Invoice, type InvoiceItem,
  type DeliveryOrder, type DeliveryOrderItem,
  type Fulfillment, type PaymentStatus,
} from '../data/sampleData'

// Marketing is a read-only role. It's listed in the DB CHECK (and in the
// Login component) but no component currently gates UI on it — the existing
// `user.role === 'admin'` checks already hide every write action from
// marketing users, so listing it here just keeps the union honest.
export type AppRole = 'admin' | 'employee' | 'marketing'

/** Row shape returned by the `v_full_set_next_due` SQL view. */
export interface DueNowRow {
  subscription_id: string
  customer_id: string
  customer_name: string
  edition_id: string
  pub_type: string
  period_label: string
  volume_count: number
  next_due_vol_num: number
  last_fulfilled_at: string | null
  start_date: string | null
  next_due_date: string
  is_due_now: boolean
  is_overdue: boolean
}

// ──────────────────────────────────────────────────────────────────────────────
// Date helpers — the app displays dates as DD/MM/YYYY everywhere; Postgres
// `date` columns come back as YYYY-MM-DD.
// ──────────────────────────────────────────────────────────────────────────────

function isoToDisplay(iso: string | null | undefined): string {
  if (!iso) return ''
  const [yyyy, mm, dd] = iso.slice(0, 10).split('-')
  if (!yyyy || !mm || !dd) return ''
  return `${dd}/${mm}/${yyyy}`
}

function displayToIso(display: string | undefined): string | null {
  if (!display) return null
  const parts = display.split('/')
  if (parts.length !== 3) return null
  const [dd, mm, yyyy] = parts
  return `${yyyy}-${mm.padStart(2, '0')}-${dd.padStart(2, '0')}`
}

// ──────────────────────────────────────────────────────────────────────────────
// Initial load — called once from App.tsx before anything else renders.
// ──────────────────────────────────────────────────────────────────────────────

export async function loadAllData(): Promise<void> {
  const [editionsRes, volumesRes, customersRes, subsRes, invoicesRes, invoiceItemsRes, doRes, doItemsRes, fulfillmentsRes] = await Promise.all([
    supabase.from('editions').select('*'),
    supabase.from('volumes').select('*'),
    supabase.from('customers').select('*'),
    supabase.from('customer_subscriptions').select('*'),
    supabase.from('invoices').select('*'),
    supabase.from('invoice_items').select('*').order('sort_order'),
    supabase.from('delivery_orders').select('*'),
    supabase.from('delivery_order_items').select('*').order('sort_order'),
    supabase.from('fulfillments').select('*'),
  ])

  for (const r of [editionsRes, volumesRes, customersRes, subsRes, invoicesRes, invoiceItemsRes, doRes, doItemsRes, fulfillmentsRes]) {
    if (r.error) throw r.error
  }

  // ---- editions + volumes ----
  const volumesByEdition = new Map<string, VolumeRecord[]>()
  for (const v of volumesRes.data ?? []) {
    const list = volumesByEdition.get(v.edition_id) ?? []
    list.push({ volNum: v.vol_num, label: v.label, stock: v.stock })
    volumesByEdition.set(v.edition_id, list)
  }
  const editionsBuilt: Edition[] = (editionsRes.data ?? []).map((e: any) => ({
    id: e.id, pubType: e.pub_type, category: e.category, year: e.year, periodLabel: e.period_label,
    volumeCount: e.volume_count, fullSetPrice: Number(e.full_set_price), pricePerVolume: Number(e.price_per_volume),
    isActive: e.is_active, isAutoGenerated: e.is_auto_generated, notes: e.notes ?? undefined,
    volumes: (volumesByEdition.get(e.id) ?? []).sort((a, b) => a.volNum - b.volNum),
  }))
  allEditions.length = 0
  allEditions.push(...editionsBuilt)

  // ---- customers + subscriptions ----
  const subsByCustomer = new Map<string, CustomerSubscription[]>()
  for (const s of subsRes.data ?? []) {
    const list = subsByCustomer.get(s.customer_id) ?? []
    list.push({ id: s.id, editionId: s.edition_id, volumeScope: s.volume_scope, startDate: s.start_date ?? '' })
    subsByCustomer.set(s.customer_id, list)
  }
  const customersBuilt: Customer[] = (customersRes.data ?? []).map((c: any) => ({
    id: c.id, invoiceNo: c.invoice_no, company: c.company, pic: c.pic ?? '', contact: c.contact ?? '',
    tin: c.tin ?? '', brn: c.brn ?? '', period: c.period ?? '', status: c.status,
    address: c.address ?? '', tel: c.tel ?? '',
    subscriptions: subsByCustomer.get(c.id) ?? [],
  }))
  customers.length = 0
  customers.push(...customersBuilt)

  // ---- invoices + items ----
  const itemsByInvoice = new Map<string, InvoiceItem[]>()
  for (const it of invoiceItemsRes.data ?? []) {
    const list = itemsByInvoice.get(it.invoice_id) ?? []
    list.push({ pub: it.pub, pubCode: it.pub_code ?? undefined, years: it.years, volumes: it.volumes, qty: it.qty, unit: Number(it.unit), total: Number(it.total) })
    itemsByInvoice.set(it.invoice_id, list)
  }
  const invoicesBuilt: Invoice[] = (invoicesRes.data ?? []).map((inv: any) => ({
    id: inv.id, invoiceNo: inv.invoice_no, date: isoToDisplay(inv.date), customer: inv.customer_name,
    customerId: inv.customer_id ?? '', address: inv.address ?? '', attention: inv.attention ?? '',
    items: itemsByInvoice.get(inv.id) ?? [],
    subtotal: Number(inv.subtotal), discount: Number(inv.discount), total: Number(inv.total),
    bank: inv.bank ?? '', account: inv.account ?? '', accountName: inv.account_name ?? '', branch: inv.branch ?? undefined,
    status: inv.status, doId: inv.do_id ?? undefined, preparedBy: inv.prepared_by ?? undefined,
    // New additive columns from migration_2026_08_subscription_backend.sql.
    // Defaults match the SQL DEFAULTs so legacy rows (written before the
    // migration ran) still pass the new CHECK constraints.
    paymentStatus: inv.payment_status ?? 'Unpaid',
    amountPaid: inv.amount_paid != null ? Number(inv.amount_paid) : 0,
    attachment: inv.attachment ?? undefined, attachmentName: inv.attachment_name ?? undefined,
  }))
  invoices.length = 0
  invoices.push(...invoicesBuilt)

  // ---- delivery orders + items ----
  const itemsByDO = new Map<string, DeliveryOrderItem[]>()
  for (const it of doItemsRes.data ?? []) {
    const list = itemsByDO.get(it.delivery_order_id) ?? []
    list.push({ pub: it.pub, pubCode: it.pub_code ?? undefined, years: it.years, volumes: it.volumes, qty: it.qty })
    itemsByDO.set(it.delivery_order_id, list)
  }
  const doBuilt: DeliveryOrder[] = (doRes.data ?? []).map((d: any) => ({
    id: d.id, doNo: d.do_no, trackingNo: d.tracking_no ?? '', date: isoToDisplay(d.date),
    customer: d.customer_name, customerId: d.customer_id ?? '', pic: d.pic ?? '', address: d.address ?? '',
    contact: d.contact ?? '', publication: d.publication ?? '', year: d.year ?? '', volume: d.volume ?? '',
    qty: d.qty, status: d.status,
    items: itemsByDO.get(d.id),
    invoiceId: d.invoice_id ?? undefined, preparedBy: d.prepared_by ?? undefined,
    // Supabase returns the column as `skip_stock_deduction`; default false
    // for any legacy row written before the column existed.
    skipStockDeduction: d.skip_stock_deduction ?? false,
    attachment: d.attachment ?? undefined, attachmentName: d.attachment_name ?? undefined,
  }))
  deliveryOrders.length = 0
  deliveryOrders.push(...doBuilt)

  // ---- fulfillments ----
  const fulfillmentsBuilt: Fulfillment[] = (fulfillmentsRes.data ?? []).map((f: any) => {
    const iso = (f.fulfilled_at ?? '').slice(0, 10)
    return {
      id: f.id, customerId: f.customer_id, editionId: f.edition_id, volNum: f.vol_num,
      fulfillmentDate: isoToDisplay(iso), fulfillmentDateIso: iso,
      unitPrice: Number(f.unit_price),
      invoiceId: f.invoice_id ?? undefined, invoiceItemId: f.invoice_item_id ?? undefined,
      preparedBy: f.prepared_by ?? undefined, notes: f.notes ?? undefined,
    }
  })
  fulfillments.length = 0
  fulfillments.push(...fulfillmentsBuilt)
}

// ──────────────────────────────────────────────────────────────────────────────
// Book Management
// ──────────────────────────────────────────────────────────────────────────────

export async function updateEditionPriceDb(editionId: string, field: 'pricePerVolume' | 'fullSetPrice', value: number): Promise<void> {
  const column = field === 'pricePerVolume' ? 'price_per_volume' : 'full_set_price'
  const { error } = await supabase.from('editions').update({ [column]: value }).eq('id', editionId)
  if (error) throw error
}

export async function updateVolumeStockDb(editionId: string, volNum: number, stock: number): Promise<void> {
  const { error } = await supabase.from('volumes').update({ stock }).eq('edition_id', editionId).eq('vol_num', volNum)
  if (error) throw error
}

export async function addVolumeDb(editionId: string, volNum: number, label: string): Promise<void> {
  const { error } = await supabase.from('volumes').insert({ edition_id: editionId, vol_num: volNum, label, stock: 0 })
  if (error) throw error
  const { error: editionErr } = await supabase.from('editions').update({ volume_count: volNum }).eq('id', editionId)
  if (editionErr) throw editionErr
}

// Deletes the given volume, then renumbers every remaining volume for that
// edition back to a clean 1..N sequence (relabeling any plain "Volume N"
// label to match), mirroring what the UI already does to the local array.
export async function deleteVolumeDb(editionId: string, deletedVolNum: number): Promise<void> {
  const { error: delErr } = await supabase.from('volumes').delete().eq('edition_id', editionId).eq('vol_num', deletedVolNum)
  if (delErr) throw delErr

  const { data, error: fetchErr } = await supabase.from('volumes').select('*').eq('edition_id', editionId).order('vol_num')
  if (fetchErr) throw fetchErr

  for (let i = 0; i < (data ?? []).length; i++) {
    const row = data![i]
    const newVolNum = i + 1
    const newLabel = /^Volume \d+$/.test(row.label) ? `Volume ${newVolNum}` : row.label
    if (row.vol_num !== newVolNum || row.label !== newLabel) {
      const { error } = await supabase.from('volumes').update({ vol_num: newVolNum, label: newLabel }).eq('id', row.id)
      if (error) throw error
    }
  }

  const { error: editionErr } = await supabase.from('editions').update({ volume_count: (data ?? []).length }).eq('id', editionId)
  if (editionErr) throw editionErr
}

// Deducts stock locally (for instant UI feedback) AND persists the same
// change to Supabase in one call — used by Create Invoice / Create Delivery
// Order right after an item is saved.
export async function deductStockAndPersist(pubType: string, periodLabel: string, volumeScope: string, qty: number): Promise<void> {
  const edition = allEditions.find(e => e.pubType === pubType && e.periodLabel === periodLabel)
  if (!edition) return
  const changes = deductStock(pubType, periodLabel, volumeScope, qty)
  for (const c of changes) {
    const { error } = await supabase.from('volumes').update({ stock: c.newStock }).eq('edition_id', edition.id).eq('vol_num', c.volNum)
    if (error) throw error
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Customers
// ──────────────────────────────────────────────────────────────────────────────

export async function insertCustomerDb(c: Customer): Promise<void> {
  const { error } = await supabase.from('customers').insert({
    id: c.id, invoice_no: c.invoiceNo, company: c.company, pic: c.pic, contact: c.contact,
    tin: c.tin, brn: c.brn, period: c.period, status: c.status, address: c.address, tel: c.tel,
  })
  if (error) throw error
}

export async function updateCustomerDb(id: string, patch: Partial<Customer>): Promise<void> {
  const payload: Record<string, unknown> = {}
  if (patch.company !== undefined) payload.company = patch.company
  if (patch.pic !== undefined) payload.pic = patch.pic
  if (patch.contact !== undefined) payload.contact = patch.contact
  if (patch.tin !== undefined) payload.tin = patch.tin
  if (patch.brn !== undefined) payload.brn = patch.brn
  if (patch.period !== undefined) payload.period = patch.period
  if (patch.status !== undefined) payload.status = patch.status
  if (patch.address !== undefined) payload.address = patch.address
  if (patch.tel !== undefined) payload.tel = patch.tel
  if (patch.invoiceNo !== undefined) payload.invoice_no = patch.invoiceNo
  const { error } = await supabase.from('customers').update(payload).eq('id', id)
  if (error) throw error
}

export async function deleteCustomerDb(id: string): Promise<void> {
  const { error } = await supabase.from('customers').delete().eq('id', id)
  if (error) throw error
}

export async function addSubscriptionDb(customerId: string, sub: CustomerSubscription): Promise<void> {
  const { error } = await supabase.from('customer_subscriptions').insert({
    id: sub.id, customer_id: customerId, edition_id: sub.editionId,
    volume_scope: sub.volumeScope, start_date: sub.startDate || null,
  })
  if (error) throw error
}

// In-place update of an existing subscription row. Matches by `id` so the
// customer's primary key (and the row in the table) is preserved — this
// is the difference between "edit" and "add" + "delete the old one":
// the user keeps the same subscription record and just changes its
// edition / volume scope / start date.
export async function updateSubscriptionDb(sub: CustomerSubscription): Promise<void> {
  const { error } = await supabase.from('customer_subscriptions').update({
    edition_id: sub.editionId,
    volume_scope: sub.volumeScope,
    start_date: sub.startDate || null,
  }).eq('id', sub.id)
  if (error) throw error
}

export async function deleteSubscriptionDb(subId: string): Promise<void> {
  const { error } = await supabase.from('customer_subscriptions').delete().eq('id', subId)
  if (error) throw error
}

// ──────────────────────────────────────────────────────────────────────────────
// Invoices
// ──────────────────────────────────────────────────────────────────────────────

function invoiceRow(inv: Invoice) {
  return {
    invoice_no: inv.invoiceNo, date: displayToIso(inv.date), customer_id: inv.customerId || null,
    customer_name: inv.customer, address: inv.address, attention: inv.attention,
    subtotal: inv.subtotal, discount: inv.discount, total: inv.total,
    bank: inv.bank, account: inv.account, account_name: inv.accountName, branch: inv.branch ?? null,
    status: inv.status, do_id: inv.doId ?? null, prepared_by: inv.preparedBy ?? null,
    // New additive columns. Defaults match the SQL DEFAULTs so writes
    // for legacy Invoice objects that don't set these still satisfy the
    // CHECK constraints.
    payment_status: inv.paymentStatus ?? 'Unpaid',
    amount_paid: inv.amountPaid ?? 0,
    attachment: inv.attachment ?? null, attachment_name: inv.attachmentName ?? null,
  }
}

export async function insertInvoiceDb(inv: Invoice): Promise<void> {
  const { error } = await supabase.from('invoices').insert({ id: inv.id, ...invoiceRow(inv) })
  if (error) throw error
  if (inv.items.length > 0) {
    const rows = inv.items.map((it, idx) => ({
      invoice_id: inv.id, pub: it.pub, pub_code: it.pubCode ?? null, years: it.years,
      volumes: it.volumes, qty: it.qty, unit: it.unit, total: it.total, sort_order: idx,
    }))
    const { error: itemsErr } = await supabase.from('invoice_items').insert(rows)
    if (itemsErr) throw itemsErr
  }
}

// Full-replace update — matches how EditInvoice already rebuilds the whole
// invoice object (including its items) on every save.
export async function updateInvoiceDb(inv: Invoice): Promise<void> {
  const { error } = await supabase.from('invoices').update(invoiceRow(inv)).eq('id', inv.id)
  if (error) throw error
  const { error: delErr } = await supabase.from('invoice_items').delete().eq('invoice_id', inv.id)
  if (delErr) throw delErr
  if (inv.items.length > 0) {
    const rows = inv.items.map((it, idx) => ({
      invoice_id: inv.id, pub: it.pub, pub_code: it.pubCode ?? null, years: it.years,
      volumes: it.volumes, qty: it.qty, unit: it.unit, total: it.total, sort_order: idx,
    }))
    const { error: itemsErr } = await supabase.from('invoice_items').insert(rows)
    if (itemsErr) throw itemsErr
  }
}

export async function deleteInvoiceDb(id: string): Promise<void> {
  const { error } = await supabase.from('invoices').delete().eq('id', id)
  if (error) throw error
}

// ──────────────────────────────────────────────────────────────────────────────
// Delivery orders
// ──────────────────────────────────────────────────────────────────────────────

function deliveryOrderRow(d: DeliveryOrder) {
  return {
    do_no: d.doNo, tracking_no: d.trackingNo, date: displayToIso(d.date),
    customer_id: d.customerId || null, customer_name: d.customer, pic: d.pic, address: d.address, contact: d.contact,
    publication: d.publication, year: d.year, volume: d.volume, qty: d.qty, status: d.status,
    invoice_id: d.invoiceId ?? null, prepared_by: d.preparedBy ?? null,
    // `?? false` keeps the DB write non-null even when the form never set
    // the flag (e.g. records created before this field existed).
    skip_stock_deduction: d.skipStockDeduction ?? false,
    attachment: d.attachment ?? null, attachment_name: d.attachmentName ?? null,
  }
}

export async function insertDeliveryOrderDb(d: DeliveryOrder): Promise<void> {
  const { error } = await supabase.from('delivery_orders').insert({ id: d.id, ...deliveryOrderRow(d) })
  if (error) throw error
  if (d.items && d.items.length > 0) {
    const rows = d.items.map((it, idx) => ({
      delivery_order_id: d.id, pub: it.pub, pub_code: it.pubCode ?? null, years: it.years,
      volumes: it.volumes, qty: it.qty, sort_order: idx,
    }))
    const { error: itemsErr } = await supabase.from('delivery_order_items').insert(rows)
    if (itemsErr) throw itemsErr
  }
}

// `itemsChanged` lets callers that only touch address/date/status (Edit
// Invoice's linked-DO panel) skip needlessly deleting+reinserting items
// they never showed or edited.
export async function updateDeliveryOrderDb(d: DeliveryOrder, itemsChanged = true): Promise<void> {
  const { error } = await supabase.from('delivery_orders').update(deliveryOrderRow(d)).eq('id', d.id)
  if (error) throw error
  if (itemsChanged) {
    const { error: delErr } = await supabase.from('delivery_order_items').delete().eq('delivery_order_id', d.id)
    if (delErr) throw delErr
    if (d.items && d.items.length > 0) {
      const rows = d.items.map((it, idx) => ({
        delivery_order_id: d.id, pub: it.pub, pub_code: it.pubCode ?? null, years: it.years,
        volumes: it.volumes, qty: it.qty, sort_order: idx,
      }))
      const { error: itemsErr } = await supabase.from('delivery_order_items').insert(rows)
      if (itemsErr) throw itemsErr
    }
  }
}

export async function deleteDeliveryOrderDb(id: string): Promise<void> {
  const { error } = await supabase.from('delivery_orders').delete().eq('id', id)
  if (error) throw error
}

// ──────────────────────────────────────────────────────────────────────────────
// App users (Login + User Management)
// ──────────────────────────────────────────────────────────────────────────────

export interface AppUserRow {
  id: string
  name: string
  email: string
  role: 'admin' | 'employee'
  status: string
  created: string
}

export async function loadAppUsers(): Promise<AppUserRow[]> {
  const { data, error } = await supabase.from('app_users').select('*').order('created_at')
  if (error) throw error
  return (data ?? []).map((u: any) => ({
    id: u.id, name: u.name, email: u.email, role: u.role, status: u.status,
    created: isoToDisplay(u.created_at),
  }))
}

// Returns the matched user's display name/role on success, or null on any
// failure (unknown email, wrong password, inactive account) — Login.tsx
// shows one generic "invalid credentials" message either way, so it never
// hints at which part was wrong.
export async function verifyLogin(email: string, password: string): Promise<{ name: string; role: 'admin' | 'employee' } | null> {
  const { data, error } = await supabase
    .from('app_users')
    .select('name, role, status, password')
    .eq('email', email)
    .maybeSingle()
  if (error) throw error
  if (!data || data.status !== 'Active' || data.password !== password) return null
  return { name: data.name, role: data.role }
}

// Server-side password change. The SQL function (see
// supabase/migration_2026_08_password.sql) verifies the current password
// and writes the new one in the same transaction — the front-end can't
// do this alone because a direct UPDATE on app_users.password would let
// anyone with the anon key (and a user's email) overwrite any password
// without knowing the current one.
export async function changeAppUserPassword(
  email: string,
  currentPassword: string,
  newPassword: string,
): Promise<void> {
  const { error } = await supabase.rpc('change_app_user_password', {
    p_email: email,
    p_current: currentPassword,
    p_new: newPassword,
  })
  if (error) throw error
}

export async function addAppUserDb(u: { name: string; email: string; role: 'admin' | 'employee' }): Promise<AppUserRow> {
  // New accounts get a placeholder password — there's no "invite by email"
  // flow here (that needs a real backend), so tell whoever's being added
  // this password out of band and have them treat it as temporary.
  const { data, error } = await supabase
    .from('app_users')
    .insert({ name: u.name, email: u.email, role: u.role, password: 'changeme123', status: 'Active' })
    .select()
    .single()
  if (error) throw error
  return { id: data.id, name: data.name, email: data.email, role: data.role, status: data.status, created: isoToDisplay(data.created_at) }
}

export async function updateAppUserDb(id: string, patch: { name?: string; email?: string; role?: string; status?: string }): Promise<void> {
  const { error } = await supabase.from('app_users').update(patch).eq('id', id)
  if (error) throw error
}

export async function deleteAppUserDb(id: string): Promise<void> {
  const { error } = await supabase.from('app_users').delete().eq('id', id)
  if (error) throw error
}

// ──────────────────────────────────────────────────────────────────────────────
// Fulfillments + Due-Now view + Invoice payment
//
// These helpers wrap the new RPC / view added in
// supabase/migration_2026_08_subscription_backend.sql. The front-end is
// free to use any of them; the existing app simply keeps working because
// nothing currently calls them yet (wiring them into screens is a
// follow-up that needs its own explicit approval, per the additive-only
// rule).
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Reads all fulfillments from Supabase, replacing the in-memory
 * `fulfillments` array in `sampleData.ts` (kept as a module-level array
 * so existing array-style reads keep working). Called once from
 * `loadAllData()`; can also be called on demand to refresh after a
 * new fulfillment is created.
 */
export async function loadFulfillments(): Promise<Fulfillment[]> {
  const { data, error } = await supabase.from('fulfillments').select('*').order('fulfilled_at', { ascending: false })
  if (error) throw error
  const built: Fulfillment[] = (data ?? []).map((f: any) => {
    const iso = (f.fulfilled_at ?? '').slice(0, 10)
    return {
      id: f.id, customerId: f.customer_id, editionId: f.edition_id, volNum: f.vol_num,
      fulfillmentDate: isoToDisplay(iso), fulfillmentDateIso: iso,
      unitPrice: Number(f.unit_price),
      invoiceId: f.invoice_id ?? undefined, invoiceItemId: f.invoice_item_id ?? undefined,
      preparedBy: f.prepared_by ?? undefined, notes: f.notes ?? undefined,
    }
  })
  fulfillments.length = 0
  fulfillments.push(...built)
  return built
}

/**
 * Reads the `v_full_set_next_due` SQL view. One row per active customer's
 * full-set subscription whose next volume isn't already fulfilled. Use
 * for the Dashboard "Due now" panel — sort client-side by `is_overdue`
 * first, then `next_due_date` ascending.
 */
export async function getDueNow(): Promise<DueNowRow[]> {
  const { data, error } = await supabase.from('v_full_set_next_due').select('*')
  if (error) throw error
  return (data ?? []) as DueNowRow[]
}

/**
 * Calls the `create_fulfillment` Postgres function. Atomic: inserts the
 * fulfillment row, decrements `volumes.stock` (clamped at 0), and
 * optionally appends an `invoice_item` to `p_invoiceId` — all in a
 * single transaction. Returns the new stock and the created
 * invoice_item_id (or null when `p_invoiceId` is null).
 *
 * Caller is expected to also call `loadFulfillments()` afterwards to
 * refresh the in-memory `fulfillments` array.
 */
export interface CreateFulfillmentArgs {
  id: string
  customerId: string
  editionId: string
  volNum: number
  unitPrice: number
  /** Optional ISO date (YYYY-MM-DD). Defaults to today. */
  fulfilledAt?: string
  invoiceId?: string | null
  preparedBy?: string | null
  notes?: string | null
}

export interface CreateFulfillmentResult {
  newStock: number
  invoiceItemId: string | null
}

export async function createFulfillmentRpc(args: CreateFulfillmentArgs): Promise<CreateFulfillmentResult> {
  const { data, error } = await supabase.rpc('create_fulfillment', {
    p_id: args.id,
    p_customer_id: args.customerId,
    p_edition_id: args.editionId,
    p_vol_num: args.volNum,
    p_unit_price: args.unitPrice,
    p_fulfilled_at: args.fulfilledAt ?? null,
    p_invoice_id: args.invoiceId ?? null,
    p_prepared_by: args.preparedBy ?? null,
    p_notes: args.notes ?? null,
  })
  if (error) throw error
  // The RPC returns a JSON object; the typed interface narrows what we use.
  const row = (data ?? {}) as { new_stock?: number; invoice_item_id?: string | null }
  return {
    newStock: typeof row.new_stock === 'number' ? row.new_stock : 0,
    invoiceItemId: row.invoice_item_id ?? null,
  }
}

/**
 * Updates the payment columns on an invoice. Enforces the
 * `amount_paid <= total` invariant in JS because Postgres CHECK can't
 * reach across to a sibling column. Caller passes the current total
 * (the DB row may have just been recomputed inside `create_fulfillment`
 * before this is called, so we don't trust a cached `inv.total`).
 */
export async function updateInvoicePayment(
  invoiceId: string,
  patch: { status?: PaymentStatus; amountPaid?: number },
  currentTotal: number,
): Promise<void> {
  if (patch.amountPaid != null) {
    if (patch.amountPaid < 0) throw new Error('amountPaid cannot be negative')
    if (patch.amountPaid > currentTotal) {
      throw new Error(`amountPaid (${patch.amountPaid}) cannot exceed invoice total (${currentTotal})`)
    }
  }
  // When status is 'Paid' the amount must equal the total. Auto-fill so
  // the caller doesn't have to do the math themselves.
  let amountPaid = patch.amountPaid
  let status = patch.status
  if (status === 'Paid' && amountPaid == null) {
    amountPaid = currentTotal
  }
  if (status === 'Paid' && amountPaid != null && amountPaid < currentTotal) {
    throw new Error('Cannot mark invoice Paid: amountPaid is less than total')
  }

  const payload: Record<string, unknown> = {}
  if (status) payload.payment_status = status
  if (amountPaid != null) payload.amount_paid = amountPaid
  if (Object.keys(payload).length === 0) return

  const { error } = await supabase.from('invoices').update(payload).eq('id', invoiceId)
  if (error) throw error
}

// ──────────────────────────────────────────────────────────────────────────────
// PDF attach (Supabase Storage)
//
// Storage shape: one object per record, key = `${recordId}.pdf`. Re-uploading
// overwrites the same key, so the row's `attachment` value stays valid across
// replaces and the old signed URL is replaced by the new file at the same
// address. Buckets are private; the front-end calls `createSignedUrl` to open
// the file in a new tab. Signed URLs default to 1 hour — long enough for a
// human to click "Open" and read; short enough that a leaked URL doesn't
// outlive the user's session.
// ──────────────────────────────────────────────────────────────────────────────

const INVOICE_PDF_BUCKET = 'invoices-pdf'
const DO_PDF_BUCKET = 'delivery-orders-pdf'
const PDF_SIGNED_URL_TTL_SECONDS = 60 * 60

/**
 * Uploads a PDF to the invoice's storage slot, then writes the key + display
 * name back onto the row. The `attachment` column is the storage object key
 * (relative to the bucket), and `attachment_name` is the original file name
 * for the UI.
 */
export async function uploadInvoicePdf(invoiceId: string, file: File): Promise<void> {
  const key = `${invoiceId}.pdf`
  const { error: upErr } = await supabase.storage
    .from(INVOICE_PDF_BUCKET)
    .upload(key, file, { contentType: 'application/pdf', upsert: true })
  if (upErr) throw upErr
  const { error: dbErr } = await supabase
    .from('invoices')
    .update({ attachment: key, attachment_name: file.name })
    .eq('id', invoiceId)
  if (dbErr) throw dbErr
  // Mirror onto the in-memory record so the UI updates without a reload.
  const inv = invoices.find(i => i.id === invoiceId)
  if (inv) { inv.attachment = key; inv.attachmentName = file.name }
}

/**
 * Returns a time-limited signed URL the admin can paste into a new tab to
 * open the attached PDF. Throws if no PDF is attached.
 */
export async function openInvoicePdf(invoiceId: string): Promise<string> {
  const inv = invoices.find(i => i.id === invoiceId)
  const key = inv?.attachment
  if (!key) throw new Error('No PDF attached to this invoice.')
  const { data, error } = await supabase.storage
    .from(INVOICE_PDF_BUCKET)
    .createSignedUrl(key, PDF_SIGNED_URL_TTL_SECONDS)
  if (error || !data?.signedUrl) throw error ?? new Error('Could not generate signed URL.')
  return data.signedUrl
}

/**
 * Removes the PDF from storage and clears the row's attachment columns.
 * Idempotent — calling on a row with no attachment is a no-op.
 */
export async function deleteInvoicePdf(invoiceId: string): Promise<void> {
  const inv = invoices.find(i => i.id === invoiceId)
  const key = inv?.attachment
  if (key) {
    const { error: delErr } = await supabase.storage
      .from(INVOICE_PDF_BUCKET)
      .remove([key])
    if (delErr) throw delErr
  }
  const { error: dbErr } = await supabase
    .from('invoices')
    .update({ attachment: null, attachment_name: null })
    .eq('id', invoiceId)
  if (dbErr) throw dbErr
  if (inv) { inv.attachment = undefined; inv.attachmentName = undefined }
}

export async function uploadDeliveryOrderPdf(doId: string, file: File): Promise<void> {
  const key = `${doId}.pdf`
  const { error: upErr } = await supabase.storage
    .from(DO_PDF_BUCKET)
    .upload(key, file, { contentType: 'application/pdf', upsert: true })
  if (upErr) throw upErr
  const { error: dbErr } = await supabase
    .from('delivery_orders')
    .update({ attachment: key, attachment_name: file.name })
    .eq('id', doId)
  if (dbErr) throw dbErr
  const d = deliveryOrders.find(x => x.id === doId)
  if (d) { d.attachment = key; d.attachmentName = file.name }
}

export async function openDeliveryOrderPdf(doId: string): Promise<string> {
  const d = deliveryOrders.find(x => x.id === doId)
  const key = d?.attachment
  if (!key) throw new Error('No PDF attached to this delivery order.')
  const { data, error } = await supabase.storage
    .from(DO_PDF_BUCKET)
    .createSignedUrl(key, PDF_SIGNED_URL_TTL_SECONDS)
  if (error || !data?.signedUrl) throw error ?? new Error('Could not generate signed URL.')
  return data.signedUrl
}

export async function deleteDeliveryOrderPdf(doId: string): Promise<void> {
  const d = deliveryOrders.find(x => x.id === doId)
  const key = d?.attachment
  if (key) {
    const { error: delErr } = await supabase.storage
      .from(DO_PDF_BUCKET)
      .remove([key])
    if (delErr) throw delErr
  }
  const { error: dbErr } = await supabase
    .from('delivery_orders')
    .update({ attachment: null, attachment_name: null })
    .eq('id', doId)
  if (dbErr) throw dbErr
  if (d) { d.attachment = undefined; d.attachmentName = undefined }
}
