-- ===================================================================
-- Seed data generated from the current in-app sample data.
-- Run this AFTER schema.sql. Safe to re-run: it clears these tables
-- first (children before parents) then re-inserts everything.
-- ===================================================================

truncate table delivery_order_items, invoice_items, customer_subscriptions, delivery_orders, invoices, volumes, editions, customers, pub_types restart identity cascade;

-- Editions
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2012', 'MLRA', 'Annual', 2012, '2012', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2013', 'MLRA', 'Annual', 2013, '2013', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2014', 'MLRA', 'Annual', 2014, '2014', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2015', 'MLRA', 'Annual', 2015, '2015', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2016', 'MLRA', 'Annual', 2016, '2016', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2017', 'MLRA', 'Annual', 2017, '2017', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2018', 'MLRA', 'Annual', 2018, '2018', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2019', 'MLRA', 'Annual', 2019, '2019', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2020', 'MLRA', 'Annual', 2020, '2020', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2021', 'MLRA', 'Annual', 2021, '2021', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2022', 'MLRA', 'Annual', 2022, '2022', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2023', 'MLRA', 'Annual', 2023, '2023', 6, 1980, 330, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2024', 'MLRA', 'Annual', 2024, '2024', 6, 1980, 330, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2025', 'MLRA', 'Annual', 2025, '2025', 6, 1980, 330, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-2026', 'MLRA', 'Annual', 2026, '2026', 6, 1980, 330, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2012', 'MLRH', 'Annual', 2012, '2012', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2013', 'MLRH', 'Annual', 2013, '2013', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2014', 'MLRH', 'Annual', 2014, '2014', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2015', 'MLRH', 'Annual', 2015, '2015', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2016', 'MLRH', 'Annual', 2016, '2016', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2017', 'MLRH', 'Annual', 2017, '2017', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2018', 'MLRH', 'Annual', 2018, '2018', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2019', 'MLRH', 'Annual', 2019, '2019', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2020', 'MLRH', 'Annual', 2020, '2020', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2021', 'MLRH', 'Annual', 2021, '2021', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2022', 'MLRH', 'Annual', 2022, '2022', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2023', 'MLRH', 'Annual', 2023, '2023', 6, 1700, 283, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2024', 'MLRH', 'Annual', 2024, '2024', 6, 1700, 283, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2025', 'MLRH', 'Annual', 2025, '2025', 6, 1700, 283, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-2026', 'MLRH', 'Annual', 2026, '2026', 6, 1700, 283, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2012', 'MELR', 'Annual', 2012, '2012', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2013', 'MELR', 'Annual', 2013, '2013', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2014', 'MELR', 'Annual', 2014, '2014', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2015', 'MELR', 'Annual', 2015, '2015', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2016', 'MELR', 'Annual', 2016, '2016', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2017', 'MELR', 'Annual', 2017, '2017', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2018', 'MELR', 'Annual', 2018, '2018', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2019', 'MELR', 'Annual', 2019, '2019', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2020', 'MELR', 'Annual', 2020, '2020', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2021', 'MELR', 'Annual', 2021, '2021', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2022', 'MELR', 'Annual', 2022, '2022', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2023', 'MELR', 'Annual', 2023, '2023', 3, 1300, 433, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2024', 'MELR', 'Annual', 2024, '2024', 3, 1300, 433, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2025', 'MELR', 'Annual', 2025, '2025', 3, 1300, 433, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MELR-2026', 'MELR', 'Annual', 2026, '2026', 3, 1300, 433, true, true, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2014', 'TCLR', 'Annual', 2014, '2014', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2015', 'TCLR', 'Annual', 2015, '2015', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2016', 'TCLR', 'Annual', 2016, '2016', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2017', 'TCLR', 'Annual', 2017, '2017', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2018', 'TCLR', 'Annual', 2018, '2018', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2019', 'TCLR', 'Annual', 2019, '2019', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2020', 'TCLR', 'Annual', 2020, '2020', 1, 700, 700, true, false, '1-volume edition (2014–2020)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2021', 'TCLR', 'Annual', 2021, '2021', 2, 1400, 700, true, false, '2-volume edition (2021 onward)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2022', 'TCLR', 'Annual', 2022, '2022', 2, 1400, 700, true, false, '2-volume edition (2021 onward)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2023', 'TCLR', 'Annual', 2023, '2023', 2, 1400, 700, true, false, '2-volume edition (2021 onward)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2024', 'TCLR', 'Annual', 2024, '2024', 2, 1400, 700, true, true, '2-volume edition (2021 onward)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2025', 'TCLR', 'Annual', 2025, '2025', 2, 1400, 700, true, true, '2-volume edition (2021 onward)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('TCLR-2026', 'TCLR', 'Annual', 2026, '2026', 2, 1400, 700, true, true, '2-volume edition (2021 onward)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('SSLR-2017', 'SSLR', 'Annual', 2017, '2017', 2, 1190, 595, true, false, 'SSLR series ended 2020 — no new editions');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('SSLR-2018', 'SSLR', 'Annual', 2018, '2018', 2, 1190, 595, true, false, 'SSLR series ended 2020 — no new editions');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('SSLR-2019', 'SSLR', 'Annual', 2019, '2019', 2, 1190, 595, true, false, 'SSLR series ended 2020 — no new editions');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('SSLR-2020', 'SSLR', 'Annual', 2020, '2020', 2, 1190, 595, true, false, 'SSLR series ended 2020 — no new editions');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1990-1991', 'MLRA', 'Selected Cases', 1990, '1990–1991', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1992-1993', 'MLRA', 'Selected Cases', 1992, '1992–1993', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1994-1995', 'MLRA', 'Selected Cases', 1994, '1994–1995', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1995', 'MLRA', 'Selected Cases', 1995, '1995', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1997', 'MLRA', 'Selected Cases', 1997, '1997', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1998', 'MLRA', 'Selected Cases', 1998, '1998', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-1999', 'MLRA', 'Selected Cases', 1999, '1999', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2000', 'MLRA', 'Selected Cases', 2000, '2000', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2001', 'MLRA', 'Selected Cases', 2001, '2001', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2002', 'MLRA', 'Selected Cases', 2002, '2002', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2003', 'MLRA', 'Selected Cases', 2003, '2003', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2004', 'MLRA', 'Selected Cases', 2004, '2004', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2005', 'MLRA', 'Selected Cases', 2005, '2005', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2006', 'MLRA', 'Selected Cases', 2006, '2006', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2007', 'MLRA', 'Selected Cases', 2007, '2007', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2008', 'MLRA', 'Selected Cases', 2008, '2008', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2009', 'MLRA', 'Selected Cases', 2009, '2009', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2010', 'MLRA', 'Selected Cases', 2010, '2010', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-SC-2011', 'MLRA', 'Selected Cases', 2011, '2011', 1, 500, 500, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1990-1991', 'MLRH', 'Selected Cases', 1990, '1990–1991', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1992-1993', 'MLRH', 'Selected Cases', 1992, '1992–1993', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1994-1995', 'MLRH', 'Selected Cases', 1994, '1994–1995', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1995', 'MLRH', 'Selected Cases', 1995, '1995', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1997', 'MLRH', 'Selected Cases', 1997, '1997', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1998', 'MLRH', 'Selected Cases', 1998, '1998', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-1999', 'MLRH', 'Selected Cases', 1999, '1999', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2000', 'MLRH', 'Selected Cases', 2000, '2000', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2001', 'MLRH', 'Selected Cases', 2001, '2001', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2002', 'MLRH', 'Selected Cases', 2002, '2002', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2003', 'MLRH', 'Selected Cases', 2003, '2003', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2004', 'MLRH', 'Selected Cases', 2004, '2004', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2005', 'MLRH', 'Selected Cases', 2005, '2005', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2006', 'MLRH', 'Selected Cases', 2006, '2006', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2007', 'MLRH', 'Selected Cases', 2007, '2007', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2008', 'MLRH', 'Selected Cases', 2008, '2008', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2009', 'MLRH', 'Selected Cases', 2009, '2009', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2010', 'MLRH', 'Selected Cases', 2010, '2010', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-SC-2011', 'MLRH', 'Selected Cases', 2011, '2011', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-CI-1990-1999', 'MLRA', 'Consolidated Index', 1990, '1990–1999', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-CI-2000-2011', 'MLRA', 'Consolidated Index', 2000, '2000–2011', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRA-CI-2012-2023', 'MLRA', 'Consolidated Index', 2012, '2012–2023', 4, 2000, 500, true, false, 'One book, 4 volumes (2012–2023)');
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-CI-1990-1999', 'MLRH', 'Consolidated Index', 1990, '1990–1999', 1, 400, 400, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-CI-2000-2011', 'MLRH', 'Consolidated Index', 2000, '2000–2011', 1, 450, 450, true, false, NULL);
insert into editions (id, pub_type, category, year, period_label, volume_count, full_set_price, price_per_volume, is_active, is_auto_generated, notes) values ('MLRH-CI-2012-2023', 'MLRH', 'Consolidated Index', 2012, '2012–2023', 4, 1800, 450, true, false, 'One book, 4 volumes (2012–2023)');

-- Volumes
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2012', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2012', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2012', 3, 'Volume 3', 5);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2012', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2012', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2012', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2013', 1, 'Volume 1', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2013', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2013', 3, 'Volume 3', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2013', 4, 'Volume 4', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2013', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2013', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2014', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2014', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2014', 3, 'Volume 3', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2014', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2014', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2014', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2015', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2015', 2, 'Volume 2', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2015', 3, 'Volume 3', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2015', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2015', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2015', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2016', 1, 'Volume 1', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2016', 2, 'Volume 2', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2016', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2016', 4, 'Volume 4', 18);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2016', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2016', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2017', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2017', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2017', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2017', 4, 'Volume 4', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2017', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2017', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2018', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2018', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2018', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2018', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2018', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2018', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2019', 1, 'Volume 1', 11);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2019', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2019', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2019', 4, 'Volume 4', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2019', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2019', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2020', 1, 'Volume 1', 11);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2020', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2020', 3, 'Volume 3', 10);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2020', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2020', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2020', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2021', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2021', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2021', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2021', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2021', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2021', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2022', 1, 'Volume 1', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2022', 2, 'Volume 2', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2022', 3, 'Volume 3', 5);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2022', 4, 'Volume 4', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2022', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2022', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2023', 1, 'Volume 1', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2023', 2, 'Volume 2', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2023', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2023', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2023', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2023', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2024', 1, 'Volume 1', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2024', 2, 'Volume 2', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2024', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2024', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2024', 5, 'Volume 5', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2024', 6, 'Volume 6', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2025', 1, 'Volume 1', 8);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2025', 2, 'Volume 2', 5);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2025', 3, 'Volume 3', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2025', 4, 'Volume 4', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2025', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2025', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2026', 1, 'Volume 1', 18);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2026', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2026', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2026', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2026', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-2026', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2012', 1, 'Volume 1', 20);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2012', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2012', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2012', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2012', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2012', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2013', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2013', 2, 'Volume 2', 29);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2013', 3, 'Volume 3', 34);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2013', 4, 'Volume 4', 9);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2013', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2013', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2014', 1, 'Volume 1', 7);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2014', 2, 'Volume 2', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2014', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2014', 4, 'Volume 4', 7);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2014', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2014', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2015', 1, 'Volume 1', 7);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2015', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2015', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2015', 4, 'Volume 4', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2015', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2015', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2016', 1, 'Volume 1', 6);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2016', 2, 'Volume 2', 17);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2016', 3, 'Volume 3', 31);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2016', 4, 'Volume 4', 11);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2016', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2016', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2017', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2017', 2, 'Volume 2', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2017', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2017', 4, 'Volume 4', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2017', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2017', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2018', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2018', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2018', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2018', 4, 'Volume 4', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2018', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2018', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2019', 1, 'Volume 1', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2019', 2, 'Volume 2', 5);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2019', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2019', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2019', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2019', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2020', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2020', 2, 'Volume 2', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2020', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2020', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2020', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2020', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2021', 1, 'Volume 1', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2021', 2, 'Volume 2', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2021', 3, 'Volume 3', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2021', 4, 'Volume 4', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2021', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2021', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2022', 1, 'Volume 1', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2022', 2, 'Volume 2', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2022', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2022', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2022', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2022', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2023', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2023', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2023', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2023', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2023', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2023', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2024', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2024', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2024', 3, 'Volume 3', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2024', 4, 'Volume 4', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2024', 5, 'Volume 5', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2024', 6, 'Volume 6', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2025', 1, 'Volume 1', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2025', 2, 'Volume 2', 22);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2025', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2025', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2025', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2025', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2026', 1, 'Volume 1', 15);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2026', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2026', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2026', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2026', 5, 'Volume 5', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-2026', 6, 'Volume 6', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2012', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2012', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2012', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2013', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2013', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2013', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2014', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2014', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2014', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2015', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2015', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2015', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2016', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2016', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2016', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2017', 1, 'Volume 1', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2017', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2017', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2018', 1, 'Volume 1', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2018', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2018', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2019', 1, 'Volume 1', 6);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2019', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2019', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2020', 1, 'Volume 1', 8);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2020', 2, 'Volume 2', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2020', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2021', 1, 'Volume 1', 10);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2021', 2, 'Volume 2', 5);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2021', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2022', 1, 'Volume 1', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2022', 2, 'Volume 2', 7);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2022', 3, 'Volume 3', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2023', 1, 'Volume 1', 14);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2023', 2, 'Volume 2', 9);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2023', 3, 'Volume 3', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2024', 1, 'Volume 1', 16);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2024', 2, 'Volume 2', 11);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2024', 3, 'Volume 3', 6);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2025', 1, 'Volume 1', 18);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2025', 2, 'Volume 2', 13);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2025', 3, 'Volume 3', 8);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2026', 1, 'Volume 1', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2026', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MELR-2026', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2014', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2015', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2016', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2017', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2018', 1, 'Volume 1', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2019', 1, 'Volume 1', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2020', 1, 'Volume 1', 6);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2021', 1, 'Volume 1', 8);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2021', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2022', 1, 'Volume 1', 10);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2022', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2023', 1, 'Volume 1', 12);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2023', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2024', 1, 'Volume 1', 14);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2024', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2025', 1, 'Volume 1', 16);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2025', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2026', 1, 'Volume 1', 10);
insert into volumes (edition_id, vol_num, label, stock) values ('TCLR-2026', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2017', 1, 'Volume 1', 3);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2017', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2018', 1, 'Volume 1', 4);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2018', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2019', 1, 'Volume 1', 5);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2019', 2, 'Volume 2', 1);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2020', 1, 'Volume 1', 6);
insert into volumes (edition_id, vol_num, label, stock) values ('SSLR-2020', 2, 'Volume 2', 2);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1990-1991', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1992-1993', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1994-1995', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1995', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1997', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1998', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-1999', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2000', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2001', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2002', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2003', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2004', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2005', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2006', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2007', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2008', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2009', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2010', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-SC-2011', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1990-1991', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1992-1993', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1994-1995', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1995', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1997', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1998', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-1999', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2000', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2001', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2002', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2003', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2004', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2005', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2006', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2007', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2008', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2009', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2010', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-SC-2011', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-CI-1990-1999', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-CI-2000-2011', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-CI-2012-2023', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-CI-2012-2023', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-CI-2012-2023', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRA-CI-2012-2023', 4, 'Volume 4', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-CI-1990-1999', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-CI-2000-2011', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-CI-2012-2023', 1, 'Volume 1', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-CI-2012-2023', 2, 'Volume 2', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-CI-2012-2023', 3, 'Volume 3', 0);
insert into volumes (edition_id, vol_num, label, stock) values ('MLRH-CI-2012-2023', 4, 'Volume 4', 0);

-- Customers
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2110', '2110', 'ADNAN SHARIDA & ASSOCIATES', 'Syed', 'Adnan Sharida', 'TIN-001-2110', '200301012345', '2025-2026', 'Active', 'Suite 12-3, Menara IMC, 8 Jalan Sultan Ismail, 50250 Kuala Lumpur', '03-2168 1234');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2208', '2208', 'SUKHDEV & ASSOCIATES', 'Syed', 'Sukhdev Singh', 'TIN-001-2208', '200401023456', '2025-2026', 'Active', 'Level 8, Wisma Hamzah-Kwong Hing, No. 1 Leboh Ampang, 50100 KL', '03-2072 5678');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2078', '2078', 'Frances Harlina & Partners', 'Syed', 'Frances Harlina', 'TIN-001-2078', '200201034567', '2025-2026', 'Active', 'No. 23, Jalan Utama 2/3, Taman Puchong Utama, 47100 Puchong', '03-8076 2345');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2019', '2019', 'A AZIDIN & SHAHRUL', 'Syed', 'Amr Sarrus Amali bin Sharif', 'TIN-001-2019', '200101045678', '2026', 'Active', '52-2, Jalan 2A/27A, Seksyen 5, Wangsa Maju, 53300 Kuala Lumpur', '03-4149 3456');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2052', '2052', 'RANBIR SSANGHA & CO', 'Syed', 'Ranbir Ssangha', 'TIN-001-2052', '200001056789', '2025-2026', 'Active', 'D-07-03, Blok D, Pusat Perniagaan Maju Junction, 50480 KL', '03-4041 4567');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2130', '2130', 'K SILA DASS & PARTNERS', 'Syed', 'K Sila Dass', 'TIN-001-2130', '199901067890', '2026', 'Active', 'No. 31-1, Jalan Segambut, 51200 Kuala Lumpur', '03-6251 5678');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2175', '2175', 'Manjit Singh Sachdev Mohammad Radzi & Partners', 'Syed', 'Manjit Singh', 'TIN-001-2175', '199801078901', '2026-2027', 'Active', 'Suite 10.01, Level 10, Menara Tan & Tan, 207 Jalan Tun Razak, 50400 KL', '03-2162 6789');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2171', '2171', 'S.O. TAN', 'Syed', 'S.O. Tan', 'TIN-001-2171', '199701089012', '2026-2027', 'Active', 'No. 12, Jalan PJS 11/28A, Bandar Sunway, 47500 Subang Jaya', '03-5621 7890');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2167', '2167', 'SHARIF & KHOO', 'Syed', 'Ahmad Sharif', 'TIN-001-2167', '199601090123', '2025', 'Active', 'Unit 13-8, Q Sentral, 2A Jalan Stesen Sentral 2, 50470 KL', '03-2785 8901');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2138', '2138', 'OTHMAN HASHIM & CO', 'Syed', 'Othman Hashim', 'TIN-001-2138', '199501101234', '2025-2026', 'Active', 'No. 45, Jalan Pahang Barat, 53000 Kuala Lumpur', '03-4043 9012');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2132', '2132', 'MATHIMUGAM, CHEE & PARTNERS', 'Syed', 'Mathimugam', 'TIN-001-2132', '199401112345', '2026-2027', 'Active', '3rd Floor, Wisma Semantan, No. 12 Lorong P Ramlee, 50250 KL', '03-2031 0123');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2191', '2191', 'KHAIRUL FADZLI AMIN & CO', 'Nadia', 'Khairul Fadzli', 'TIN-001-2191', '199301123456', '2026', 'Active', 'No. 71-1, Jalan Besar, 28000 Temerloh, Pahang', '09-2965 1234');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2181', '2181', 'V.M. MUTHU & CO', 'Syed', 'V.M. Muthu', 'TIN-001-2181', '199201134567', '2026', 'Active', 'No. 18, Jalan 51/A/223, Seksyen 51A, 46100 Petaling Jaya', '03-7785 2345');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2058', '2058', 'Mahkamah Perusahaan Malaysia', 'Syed', 'Ketua Pendaftar', 'TIN-GOV-2058', 'GOV-00012345', '2024-2025', 'Complete', 'Aras 2-16, Blok D, Kompleks Pejabat Damansara, 50490 Kuala Lumpur', '03-2052 3456');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2055', '2055', 'Tenaga Nasional Berhad', 'Syed', 'Corporate Library', 'TIN-001-2055', '199001000007', '2025-2026', 'Active', 'No. 129, Jalan Bangsar, 59200 Kuala Lumpur', '03-2296 5000');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2176', '2176', 'Genting Malaysia Berhad', 'Syed', 'Legal Department', 'TIN-001-2176', '197901001526', '2026-2028', 'Active', 'Level 17, Wisma Genting, Jalan Sultan Ismail, 50250 Kuala Lumpur', '03-2333 6000');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2196', '2196', 'Juel Dhillon & Co', 'Nadia', 'Juel Dhillon', 'TIN-001-2196', '200501145678', '2026-2027', 'Active', 'No. 3-2, Jalan Puteri 2/3, Bandar Puteri Puchong, 47100 Puchong', '03-8062 3456');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2200', '2200', 'G. Ram Rozzeta & Associates', 'Syed', 'G. Ram Rozzeta', 'TIN-001-2200', '200601156789', '2026-2027', 'Active', 'B-3A-5, Blok B, Megan Avenue II, 12 Jalan Yap Kwan Seng, 50450 KL', '03-2166 4567');
insert into customers (id, invoice_no, company, pic, contact, tin, brn, period, status, address, tel) values ('2203', '2203', 'Lee Hishamuddin Allen & Gledhill (Sharifullah)', 'Yathwin/Effe', 'Sharifullah', 'TIN-001-2203', '196401167890', '2025', 'Complete', 'Level 23, Mercu 3, No. 3, Jalan Bangsar, KL Eco City, 59200 KL', '03-2081 5678');

-- Customer subscriptions
insert into customer_subscriptions (id, customer_id, edition_id, volume_scope, start_date) values ('SUB-2110-1', '2110', 'MLRH-2025', 'Full Set', '2025-02-01');
insert into customer_subscriptions (id, customer_id, edition_id, volume_scope, start_date) values ('SUB-2019-1', '2019', 'MLRA-2023', 'Full Set', '2023-01-15');
insert into customer_subscriptions (id, customer_id, edition_id, volume_scope, start_date) values ('SUB-2055-1', '2055', 'MLRA-2025', 'Full Set', '2025-01-01');
insert into customer_subscriptions (id, customer_id, edition_id, volume_scope, start_date) values ('SUB-2055-2', '2055', 'MLRH-2025', 'Full Set', '2025-01-01');

-- Invoices (do_id patched in after delivery_orders are inserted below)
insert into invoices (id, invoice_no, date, customer_id, customer_name, address, attention, subtotal, discount, total, bank, account, account_name, branch, status, prepared_by) values ('INV-2019', '2019/MLRA/2026', '2026-02-06', '2019', 'A AZIDIN & SHAHRUL', '52-2, Jalan 2A/27A, Seksyen 5, Wangsa Maju, 53300 Kuala Lumpur', 'Amr Sarrus Amali bin Sharif', 10160, 0, 10160, 'Public Bank', '3165991104', 'The Legal Review Sdn Bhd', 'Taman Melawati, Kuala Lumpur, Malaysia', 'Pending', 'Ain Shuhada');
insert into invoices (id, invoice_no, date, customer_id, customer_name, address, attention, subtotal, discount, total, bank, account, account_name, branch, status, prepared_by) values ('INV-2110', '2110/MLRA/2026', '2026-02-12', '2110', 'ADNAN SHARIDA & ASSOCIATES', 'Suite 12-3, Menara IMC, 8 Jalan Sultan Ismail, 50250 Kuala Lumpur', 'Adnan Sharida', 2230, 100, 2130, 'Public Bank', '3165991104', 'The Legal Review Sdn Bhd', 'Taman Melawati, Kuala Lumpur, Malaysia', 'Pending', 'Ain Shuhada');
insert into invoices (id, invoice_no, date, customer_id, customer_name, address, attention, subtotal, discount, total, bank, account, account_name, branch, status, prepared_by) values ('INV-2055', '2055/MLRA/2026', '2026-02-18', '2055', 'Tenaga Nasional Berhad', 'No. 129, Jalan Bangsar, 59200 Kuala Lumpur', 'Corporate Library', 3930, 0, 3930, 'Public Bank', '3165991104', 'The Legal Review Sdn Bhd', 'Taman Melawati, Kuala Lumpur, Malaysia', 'Pending', 'Ain Shuhada');

-- Invoice items
insert into invoice_items (invoice_id, pub, pub_code, years, volumes, qty, unit, total, sort_order) values ('INV-2019', 'The Malaysian Law Review Appellate Court', NULL, '2017-2018', '12 Volumes', 12, 371.67, 4460, 0);
insert into invoice_items (invoice_id, pub, pub_code, years, volumes, qty, unit, total, sort_order) values ('INV-2019', 'The Malaysian Law Review High Court (MLRH)', NULL, '2017-2018', '12 Volumes', 12, 283.33, 3400, 1);
insert into invoice_items (invoice_id, pub, pub_code, years, volumes, qty, unit, total, sort_order) values ('INV-2019', 'The Commonwealth Law Review (1-3)', NULL, '2017-2018', '3 Volumes', 3, 766.67, 2300, 2);
insert into invoice_items (invoice_id, pub, pub_code, years, volumes, qty, unit, total, sort_order) values ('INV-2110', 'The Malaysian Law Review Appellate Court', NULL, '2025-2026', '6 Volumes', 6, 371.67, 2230, 0);
insert into invoice_items (invoice_id, pub, pub_code, years, volumes, qty, unit, total, sort_order) values ('INV-2055', 'The Malaysian Law Review Appellate Court', NULL, '2025-2026', 'Full Set', 1, 2230, 2230, 0);
insert into invoice_items (invoice_id, pub, pub_code, years, volumes, qty, unit, total, sort_order) values ('INV-2055', 'The Malaysian Law Review High Court (MLRH)', NULL, '2025-2026', 'Full Set', 1, 1700, 1700, 1);

-- Delivery orders
insert into delivery_orders (id, do_no, tracking_no, date, customer_id, customer_name, pic, address, contact, publication, year, volume, qty, status, invoice_id, prepared_by) values ('DO-2138', 'DO-2138', 'TRK-20260218-3847', '2026-02-18', '2138', 'Mathews & Associates', 'Mr. Joseph Mathews', 'No. 501-C, Jalan S2 D6, Magistrate''s Square, Seremban 2, 70300 Seremban 2, Negeri Sembilan', '06-7653041', 'Malaysian Law Review (Appellate Court)', '2025', 'Volume 1', 1, 'Delivered', NULL, 'Ain Shuhada');
insert into delivery_orders (id, do_no, tracking_no, date, customer_id, customer_name, pic, address, contact, publication, year, volume, qty, status, invoice_id, prepared_by) values ('DO-2110', 'DO-2110', 'TRK-20260220-1192', '2026-02-20', '2110', 'ADNAN SHARIDA & ASSOCIATES', 'Adnan Sharida', 'Suite 12-3, Menara IMC, 8 Jalan Sultan Ismail, 50250 Kuala Lumpur', '03-2168 1234', 'Malaysian Law Review (Appellate Court)', '2025', 'Volume 1', 1, 'Processing', 'INV-2110', 'Ain Shuhada');
insert into delivery_orders (id, do_no, tracking_no, date, customer_id, customer_name, pic, address, contact, publication, year, volume, qty, status, invoice_id, prepared_by) values ('DO-2055', 'DO-2055', 'TRK-20260225-5531', '2026-02-25', '2055', 'Tenaga Nasional Berhad', 'Corporate Library', 'No. 129, Jalan Bangsar, 59200 Kuala Lumpur', '03-2296 5000', 'The Malaysian Law Review High Court (MLRH)', '2025', 'Volume 2', 1, 'Processing', 'INV-2055', 'Ain Shuhada');
insert into delivery_orders (id, do_no, tracking_no, date, customer_id, customer_name, pic, address, contact, publication, year, volume, qty, status, invoice_id, prepared_by) values ('DO-2019', 'DO-2019', 'TRK-20260228-7734', '2026-02-28', '2019', 'A AZIDIN & SHAHRUL', 'Amr Sarrus Amali bin Sharif', '52-2, Jalan 2A/27A, Seksyen 5, Wangsa Maju, 53300 Kuala Lumpur', '03-4149 3456', 'The Malaysian Law Review Appellate Court', '2026', 'Volume 1', 2, 'Pending', 'INV-2019', 'Ain Shuhada');

-- Delivery order items

-- Link invoices to their delivery orders now that both tables are populated
update invoices set do_id = 'DO-2019' where id = 'INV-2019';
update invoices set do_id = 'DO-2110' where id = 'INV-2110';
update invoices set do_id = 'DO-2055' where id = 'INV-2055';


-- Pub-type registry (seed-side mirror of the 5 originals in
-- migration_2026_09_edition_admin.sql). Truncate at the top clears this
-- table too, so the seed below restarts from a known state every run.
truncate table pub_types restart identity;
insert into pub_types (code, label) values
  ('MLRA', 'Malaysian Law Review (Appellate Court)'),
  ('MLRH', 'Malaysian Law Review (High Court)'),
  ('MELR', 'Malaysian Employment Law Reports'),
  ('TCLR', 'The Commonwealth Law Review'),
  ('SSLR', 'Sabah Sarawak Law Review')
on conflict (code) do nothing;

-- App users — passwords set to match the app's previous hardcoded demo
-- logins where they existed; the rest get a placeholder you should change
-- on first login (there's no "change password" screen yet — update these
-- rows directly in the Supabase Table Editor for now).
truncate table app_users restart identity cascade;
insert into app_users (name, email, password, role, status, department, created_at) values ('Ain Shuhada', 'admin@legalreview.com.my', 'admin123', 'admin', 'Active', 'Editorial', '2024-01-01');
insert into app_users (name, email, password, role, status, department, created_at) values ('Syed Izzat', 'staff@legalreview.com.my', 'staff123', 'employee', 'Active', 'Subscriptions', '2024-03-15');
insert into app_users (name, email, password, role, status, department, created_at) values ('Nadia Hanim', 'nadia@legalreview.com.my', 'changeme123', 'employee', 'Active', 'Subscriptions', '2024-06-01');
insert into app_users (name, email, password, role, status, department, created_at) values ('Yathwin Lim', 'yathwin@legalreview.com.my', 'changeme123', 'employee', 'Active', 'Fulfilment', '2024-07-10');
insert into app_users (name, email, password, role, status, department, created_at) values ('Effendy Razak', 'effe@legalreview.com.my', 'changeme123', 'employee', 'Inactive', 'Fulfilment', '2024-08-20');
