// Book Management types and pure helpers. The actual edition/volume data
// used to be computed here by generator functions at module load — it now
// lives in Supabase (see supabase/schema.sql + supabase/seed.sql) and is
// loaded into `allEditions` once at app startup by src/lib/db.ts's
// loadAllData(). Everything below just operates on whatever is currently
// in that array, so Book Management edits (price changes, added/removed
// volumes, stock updates) are reflected everywhere immediately, exactly as
// before — the only difference is where the array gets filled from.

export type PubType = 'MLRA' | 'MLRH' | 'MELR' | 'TCLR' | 'SSLR'
export type BoundCategory = 'Annual' | 'Selected Cases' | 'Consolidated Index'

export interface VolumeRecord {
  volNum: number
  label: string
  stock: number
}

export interface Edition {
  id: string
  pubType: PubType
  category: BoundCategory
  year: number
  periodLabel: string
  volumeCount: number
  fullSetPrice: number
  pricePerVolume: number
  isActive: boolean
  isAutoGenerated: boolean
  volumes: VolumeRecord[]
  notes?: string
}

// Populated by loadAllData() in src/lib/db.ts. Kept as the same array
// reference throughout the app's lifetime (cleared + re-pushed on reload,
// never reassigned) so every `import { allEditions }` elsewhere always sees
// the current data without needing its own fetch.
export const allEditions: Edition[] = []

export const PUB_LABELS: Record<PubType, string> = {
  MLRA: 'Malaysian Law Review (Appellate Court)',
  MLRH: 'Malaysian Law Review (High Court)',
  MELR: 'Malaysian Employment Law Reports',
  TCLR: 'The Commonwealth Law Review',
  SSLR: 'Sultan Sharafuddin Law Review',
}

export const LOW_STOCK = 10

export function computeFullSet(volumes: VolumeRecord[]): number {
  if (volumes.length === 0) return 0
  if (volumes.some(v => v.stock === 0)) return 0
  return Math.min(...volumes.map(v => v.stock))
}

export interface LowStockVolume {
  editionId: string
  pubType: PubType
  periodLabel: string
  category: BoundCategory
  volNum: number
  label: string
  stock: number
}

// Live view of every individual volume currently at or below the low-stock
// threshold, across every publication/category. Reads `allEditions`
// directly each call, so it always reflects whatever was last edited in
// Book Management — nothing here is a snapshot.
export function getLowStockVolumes(): LowStockVolume[] {
  const rows: LowStockVolume[] = []
  for (const e of allEditions) {
    for (const v of e.volumes) {
      if (v.stock < LOW_STOCK) {
        rows.push({
          editionId: e.id, pubType: e.pubType, periodLabel: e.periodLabel,
          category: e.category, volNum: v.volNum, label: v.label, stock: v.stock,
        })
      }
    }
  }
  return rows.sort((a, b) => a.stock - b.stock)
}

// Live per-publication totals (summed across every category/edition),
// used by the Dashboard and Reports so book management edits are reflected
// immediately instead of a stale copy of the numbers.
export function getStockTotalsByPub(): Record<PubType, { totalStock: number; zeroStockVolumes: number; lowStockVolumes: number }> {
  const totals = {} as Record<PubType, { totalStock: number; zeroStockVolumes: number; lowStockVolumes: number }>
  for (const p of Object.keys(PUB_LABELS) as PubType[]) {
    totals[p] = { totalStock: 0, zeroStockVolumes: 0, lowStockVolumes: 0 }
  }
  for (const e of allEditions) {
    for (const v of e.volumes) {
      totals[e.pubType].totalStock += v.stock
      if (v.stock === 0) totals[e.pubType].zeroStockVolumes++
      else if (v.stock < LOW_STOCK) totals[e.pubType].lowStockVolumes++
    }
  }
  return totals
}

// ──────────────────────────────────────────────────────────────────────────────
// Stock lookup / local deduction — used by Create Invoice and Create
// Delivery Order so admins see live Book Management availability (including
// "Out of Stock") while picking items. These only touch the in-memory
// array; src/lib/db.ts's deductStockDb() is what actually persists a
// deduction to Supabase — the two are called together at every call site.
// ──────────────────────────────────────────────────────────────────────────────

export interface StockInfo { available: number; outOfStock: boolean }

// `volumeScope` is either 'Full Set' or 'Volume N' (same convention used by
// invoice/DO line items and customer subscriptions).
export function getStockInfo(pubType: string, periodLabel: string, volumeScope: string): StockInfo | null {
  if (!pubType || !periodLabel || !volumeScope) return null
  const edition = allEditions.find(e => e.pubType === pubType && e.periodLabel === periodLabel)
  if (!edition) return null
  if (volumeScope.toLowerCase().includes('full')) {
    const available = computeFullSet(edition.volumes)
    return { available, outOfStock: available <= 0 }
  }
  const match = /Volume\s*(\d+)/i.exec(volumeScope)
  if (!match) return null
  const vol = edition.volumes.find(v => v.volNum === Number(match[1]))
  if (!vol) return null
  return { available: vol.stock, outOfStock: vol.stock <= 0 }
}

// Deducts `qty` from the LOCAL copy of stock for a specific pub+year+
// volume-scope combination, for immediate UI feedback. 'Full Set' deducts
// one full set's worth from every volume in the edition; a specific volume
// deducts only from that volume. Stock is clamped at 0. Returns the list of
// (volNum, newStock) pairs actually changed, so the caller can persist the
// same change to Supabase via deductStockDb().
export function deductStock(pubType: string, periodLabel: string, volumeScope: string, qty: number): { volNum: number; newStock: number }[] {
  if (!pubType || !periodLabel || !volumeScope || !qty || qty <= 0) return []
  const edition = allEditions.find(e => e.pubType === pubType && e.periodLabel === periodLabel)
  if (!edition) return []
  const changed: { volNum: number; newStock: number }[] = []
  if (volumeScope.toLowerCase().includes('full')) {
    edition.volumes.forEach(v => {
      v.stock = Math.max(0, v.stock - qty)
      changed.push({ volNum: v.volNum, newStock: v.stock })
    })
    return changed
  }
  const match = /Volume\s*(\d+)/i.exec(volumeScope)
  if (!match) return []
  const vol = edition.volumes.find(v => v.volNum === Number(match[1]))
  if (vol) {
    vol.stock = Math.max(0, vol.stock - qty)
    changed.push({ volNum: vol.volNum, newStock: vol.stock })
  }
  return changed
}
